# Generated by Django 5.2.5 on 2025-09-02 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(db_column='T001IdPersona', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='t001Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='t001Apellido', max_length=100)),
                ('documento', models.CharField(db_column='t001Documento', max_length=100)),
                ('email', models.CharField(db_column='t001Email', max_length=100)),
                ('activo', models.CharField(db_column='t001Activo', max_length=100)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'T001Persona',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(db_column='TO02IdTarea', editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='T®2Titulo', max_length=200)),
                ('descripcion', models.TextField(db_column='T®2Descripcion')),
                ('fecha_limite', models.DateField(db_column='T®2FechaLimite')),
                ('persona', models.ForeignKey(db_column='TO2Personald', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='api_app.persona')),
            ],
        ),
    ]
