# Generated by Django 5.2.5 on 2025-09-02 23:42

import django.db.models.deletion
from django.db import migrations, models

#migraciones
class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='id_tarea',
        ),
        migrations.AddField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.persona'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
